os:
    - osx
    - windows
language: node_js
node_js:
    - 12
cache:
    yarn: true
env:
    - YARN_GPG=no
branches:
    only:
        - master
        - prefix-flow

script:
    - cd renderer
    # - yarn install
    # - cd ..
    # - yarn install
    # - yarn run pack:$TRAVIS_OS_NAME

jobs:
  include:
    - stage: npm release
      if: branch = prefix-flow
      os: osx
      before_deploy:
        - cd replayer
      deploy:
        provider: npm
        dry_run: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: prefix-flow
