os:
    - osx
    - windows
language: node_js
node_js:
    - 12
cache:
    yarn: true

jobs:
    include:
        - stage: script
# - stage: deploy

script:
    - cd renderer
    - yarn install
    - cd ..
    - yarn install
    - yarn run pack:$TRAVIS_OS_NAME

after_script:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then taskkill //F //PID $(ps -Wla | tr -s ' ' | grep gpg | cut-f2 -d' '); fi

# deploy:
#   provider: releases
#   api_key:
#     secure: YOUR_API_KEY_ENCRYPTED
#   file:
#     - dist/*.zip
#     - dist/*.exe
#   skip_cleanup: true
#   draft: true

