name: TestNpmPublish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd replayer
      - uses: actions/cache@v1
        with:
          path: replayer/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('replayer/package.json') }}
      - run: yarn install
